# Clean Data

### Import libraries and install dependencies:

In [6]:
import pandas as pd

### Load datasets:

In [ ]:
data_df = pd.read_excel("../mutations-raw.xlsx", header=2)  
identifier_df = pd.read_csv("../identifier.csv", sep=';') # Load the gene identifier

/Users/I586426/Desktop/personal/Projects/veriMasterDegreeTools/preprocess/.venv/lib/python3.12/site-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)

### Preprocessing datasets:

In [9]:
data_df.head()  # Display the first few rows of the dataset

,drug,gene,mutation,variant,tier,effect,genomic position,algorithm_pass,Present_SOLO_SR,Present_SOLO_R,...,Additional grading criteria applied,FINAL CONFIDENCE GRADING,Comment,CHANGES vs ver1,"Relaxed thresholds simulation (BDQ_Rv0678, CFZ_Rv0678, INH_katG, DLM_ddn/fbiA/fbiB/fbiC/fgd1/Rv2983)",Silent mutation,Listed in abridged tables,Additional grading,Footnote,CHANGES vs ver1.1
0,Amikacin,bacA,c.102G>A,bacA_c.102G>A,2,synonymous_variant,"(see ""Genomic_coordinates"" sheet)",NaN,NaN,NaN,...,Silent mutation,4) Not assoc w R - Interim,NaN,Now listed,NaN,Silent mutation,no,NaN,NaN,0
1,Amikacin,bacA,c.1044G>A,bacA_c.1044G>A,2,synonymous_variant,"(see ""Genomic_coordinates"" sheet)",NaN,NaN,NaN,...,NaN,5) Not assoc w R,NaN,Now listed,NaN,Silent mutation,no,NaN,NaN,0
2,Amikacin,bacA,c.105C>G,bacA_c.105C>G,2,synonymous_variant,"(see ""Genomic_coordinates"" sheet)",NaN,NaN,NaN,...,Silent mutation,4) Not assoc w R - Interim,NaN,Now listed,NaN,Silent mutation,no,NaN,NaN,0
3,Amikacin,bacA,c.1065T>G,bacA_c.1065T>G,2,synonymous_variant,"(see ""Genomic_coordinates"" sheet)",NaN,NaN,NaN,...,Silent mutation,4) Not assoc w R - Interim,NaN,Now listed,NaN,Silent mutation,no,NaN,NaN,0
4,Amikacin,bacA,c.1080G>A,bacA_c.1080G>A,2,synonymous_variant,"(see ""Genomic_coordinates"" sheet)",NaN,NaN,NaN,...,Silent mutation,4) Not assoc w R - Interim,NaN,Now listed,NaN,Silent mutation,no,NaN,NaN,0

In [10]:
print(f"Dataset shape: {data_df.shape}")  # Print the shape of the dataset
print(f"Rows: {data_df.shape[0]}")  # Print the number of rows
print(f"Columns: {data_df.shape[1]}")  # Print the number of columns

Dataset shape: (48152, 114)
Rows: 48152
Columns: 114

Filter wanted columns:
- gene
- variant
- effect
- FINAL CONFIDENCE GRADING

In [11]:
columns = ['gene', 'variant', 'effect', 'FINAL CONFIDENCE GRADING']  # Define the columns to keep
data_df = data_df[columns]  # Filter the dataset to keep only the wanted columns

In [12]:
data_df.head()  # Display the first few rows of the filtered dataset

   gene         variant              effect    FINAL CONFIDENCE GRADING
0  bacA   bacA_c.102G>A  synonymous_variant  4) Not assoc w R - Interim
1  bacA  bacA_c.1044G>A  synonymous_variant            5) Not assoc w R
2  bacA   bacA_c.105C>G  synonymous_variant  4) Not assoc w R - Interim
3  bacA  bacA_c.1065T>G  synonymous_variant  4) Not assoc w R - Interim
4  bacA  bacA_c.1080G>A  synonymous_variant  4) Not assoc w R - Interim

In [13]:
data_df.describe()  # Display summary statistics of the filtered dataset

,gene,variant,effect,FINAL CONFIDENCE GRADING
count,48152,48152,48152,48152
unique,65,30699,14,5
top,Rv2752c,Rv2477c_p.Glu476Ala,missense_variant,3) Uncertain significance
freq,3974,7,23065,33906

Merge identifiers dataframe with data

In [14]:
data_df = data_df.merge(identifier_df, on='gene', how='inner')  # Merge the dataframes on the 'gene' column
data_df.head()  # Display the first few rows of the merged dataset

,gene,variant,effect,FINAL CONFIDENCE GRADING,identifier
0,bacA,bacA_c.102G>A,synonymous_variant,4) Not assoc w R - Interim,Rv1819c
1,bacA,bacA_c.1044G>A,synonymous_variant,5) Not assoc w R,Rv1819c
2,bacA,bacA_c.105C>G,synonymous_variant,4) Not assoc w R - Interim,Rv1819c
3,bacA,bacA_c.1065T>G,synonymous_variant,4) Not assoc w R - Interim,Rv1819c
4,bacA,bacA_c.1080G>A,synonymous_variant,4) Not assoc w R - Interim,Rv1819c

In [15]:
print(f"Dataset shape: {data_df.shape}")  # Print the shape of the merged dataset
print(f"Rows: {data_df.shape[0]}")  # Print the number of rows in the merged dataset
print(f"Columns: {data_df.shape[1]}")  # Print the number of columns in the merged dataset

Dataset shape: (48152, 5)
Rows: 48152
Columns: 5

In [16]:
data_df.describe()  # Display summary statistics of the merged dataset

,gene,variant,effect,FINAL CONFIDENCE GRADING,identifier
count,48152,48152,48152,48152,48152
unique,65,30699,14,5,65
top,Rv2752c,Rv2477c_p.Glu476Ala,missense_variant,3) Uncertain significance,Rv2752c
freq,3974,7,23065,33906,3974

In [17]:
data_df.describe()  # Display summary statistics of the merged dataset

,gene,variant,effect,FINAL CONFIDENCE GRADING,identifier
count,48152,48152,48152,48152,48152
unique,65,30699,14,5,65
top,Rv2752c,Rv2477c_p.Glu476Ala,missense_variant,3) Uncertain significance,Rv2752c
freq,3974,7,23065,33906,3974

Create dataset for all wild types

In [18]:
complete_wild_df = data_df[['gene', 'identifier']].copy()  # Create a copy of the 'gene' and 'identifier' columns
complete_wild_df = complete_wild_df.drop_duplicates(subset='gene')  # Drop duplicate rows based on the 'gene' column
complete_wild_df['mycobrowser_url'] = 'https://mycobrowser.epfl.ch/genes/' + complete_wild_df['identifier']  # Add a new column with URLs
complete_wild_df.head()  # Display the first few rows of the complete wild dataset

         gene identifier                              mycobrowser_url
0        bacA    Rv1819c    https://mycobrowser.epfl.ch/genes/Rv1819c
244      ccsA     Rv0529     https://mycobrowser.epfl.ch/genes/Rv0529
413       eis    Rv2416c    https://mycobrowser.epfl.ch/genes/Rv2416c
669       rrs  MTB000019  https://mycobrowser.epfl.ch/genes/MTB000019
1335  Rv2477c    Rv2477c    https://mycobrowser.epfl.ch/genes/Rv2477c

In [19]:
print(f"Dataset shape: {complete_wild_df.shape}")  # Print the shape of the complete wild dataset
print(f"Rows: {complete_wild_df.shape[0]}")  # Print the number of rows in the complete wild dataset
print(f"Columns: {complete_wild_df.shape[1]}")  # Print the number of columns in the complete wild dataset

Dataset shape: (65, 3)
Rows: 65
Columns: 3

In [83]:
print(f"Dataset shape: {complete_wild_df.shape}")
print(f"Rows: {complete_wild_df.shape[0]}")
print(f"Columns: {complete_wild_df.shape[1]}")

In [84]:
complete_wild_df.describe()  # Display summary statistics of the complete wild dataset

Creating dataset for all variants

In [20]:
complete_variant_df = data_df[['gene', 'identifier', 'variant', 'effect', 'FINAL CONFIDENCE GRADING']].copy()  # Create a copy of the relevant columns
complete_wild_df = complete_wild_df.drop_duplicates()  # Drop duplicate rows
complete_variant_df = complete_variant_df.rename(columns={'FINAL CONFIDENCE GRADING': 'final_confidence_grading'})  # Rename a column
complete_variant_df.head()  # Display the first few rows of the complete variant dataset

,gene,identifier,variant,effect,final_confidence_grading
0,bacA,Rv1819c,bacA_c.102G>A,synonymous_variant,4) Not assoc w R - Interim
1,bacA,Rv1819c,bacA_c.1044G>A,synonymous_variant,5) Not assoc w R
2,bacA,Rv1819c,bacA_c.105C>G,synonymous_variant,4) Not assoc w R - Interim
3,bacA,Rv1819c,bacA_c.1065T>G,synonymous_variant,4) Not assoc w R - Interim
4,bacA,Rv1819c,bacA_c.1080G>A,synonymous_variant,4) Not assoc w R - Interim

In [21]:
complete_variant_df.head()

,gene,identifier,variant,effect,final_confidence_grading
0,bacA,Rv1819c,bacA_c.102G>A,synonymous_variant,4) Not assoc w R - Interim
1,bacA,Rv1819c,bacA_c.1044G>A,synonymous_variant,5) Not assoc w R
2,bacA,Rv1819c,bacA_c.105C>G,synonymous_variant,4) Not assoc w R - Interim
3,bacA,Rv1819c,bacA_c.1065T>G,synonymous_variant,4) Not assoc w R - Interim
4,bacA,Rv1819c,bacA_c.1080G>A,synonymous_variant,4) Not assoc w R - Interim

In [22]:
print(f"Dataset shape: {complete_variant_df.shape}")  # Print the shape of the complete variant dataset
print(f"Rows: {complete_variant_df.shape[0]}")  # Print the number of rows in the complete variant dataset
print(f"Columns: {complete_variant_df.shape[1]}")  # Print the number of columns in the complete variant dataset

Dataset shape: (48152, 5)
Rows: 48152
Columns: 5

In [23]:
complete_variant_df.describe()  # Display summary statistics of the complete variant dataset

,gene,identifier,variant,effect,final_confidence_grading
count,48152,48152,48152,48152,48152
unique,65,65,30699,14,5
top,Rv2752c,Rv2752c,Rv2477c_p.Glu476Ala,missense_variant,3) Uncertain significance
freq,3974,3974,7,23065,33906

Analyse columns:

In [24]:
print(f"Unique genes: {data_df['gene'].unique()}")  # Print unique genes
print(f"Unique final confidence: {data_df['FINAL CONFIDENCE GRADING'].unique()}")  # Print unique final confidence gradings
print(f"Unique effect: {data_df['effect'].unique()}")  # Print unique effects

Unique genes: ['bacA' 'ccsA' 'eis' 'rrs' 'Rv2477c' 'whiB6' 'whiB7' 'atpE' 'lpqB' 'mmpL5'
 'mmpS5' 'mtrA' 'mtrB' 'pepQ' 'Rv0678' 'Rv1979c' 'rrl' 'Rv2680' 'Rv2681'
 'tlyA' 'fbiA' 'fbiB' 'fbiC' 'fgd1' 'Rv2983' 'ddn' 'ndh' 'aftB' 'embA'
 'embB' 'embC' 'embR' 'glpK' 'Rv2752c' 'ubiA' 'ethA' 'ethR' 'inhA' 'mshA'
 'Rv0565c' 'Rv3083' 'ahpC' 'dnaA' 'hadA' 'katG' 'Rv0010c' 'Rv1129c'
 'Rv1258c' 'gyrA' 'gyrB' 'rplC' 'tsnR' 'clpC1' 'panD' 'pncA' 'PPE35'
 'rpsA' 'Rv3236c' 'sigE' 'nusG' 'rpoA' 'rpoB' 'rpoC' 'gid' 'rpsL']
Unique final confidence: ['4) Not assoc w R - Interim' '5) Not assoc w R'
 '3) Uncertain significance' '2) Assoc w R - Interim' '1) Assoc w R']
Unique effect: ['synonymous_variant' 'upstream_gene_variant' 'stop_retained_variant'
 'feature_ablation' 'LoF' 'missense_variant' 'frameshift' 'stop_gained'
 'inframe_insertion' 'initiator_codon_variant' 'start_lost'
 'inframe_deletion' 'non_coding_transcript_exon_variant' 'stop_lost']

In [25]:
print(f"Unique final confidence: {data_df['FINAL CONFIDENCE GRADING'].unique()}")

Unique final confidence: ['4) Not assoc w R - Interim' '5) Not assoc w R'
 '3) Uncertain significance' '2) Assoc w R - Interim' '1) Assoc w R']

In [26]:
print(f"Unique effect: {data_df['effect'].unique()}")

Unique effect: ['synonymous_variant' 'upstream_gene_variant' 'stop_retained_variant'
 'feature_ablation' 'LoF' 'missense_variant' 'frameshift' 'stop_gained'
 'inframe_insertion' 'initiator_codon_variant' 'start_lost'
 'inframe_deletion' 'non_coding_transcript_exon_variant' 'stop_lost']

Filter Values:
- effect = `missense_variant`
- FINAL CONFIDENCE GRADING = `1) Assoc w R` or `2) Assoc w R - Interim`

In [27]:
data_df = data_df[(data_df['effect'] == 'missense_variant') & (data_df['FINAL CONFIDENCE GRADING'].isin(['2) Assoc w R - Interim', '1) Assoc w R']))]  # Filter the dataset based on specific conditions

Analyse new dataset

In [28]:
data_df.head()  # Display the first few rows of the filtered dataset

,gene,variant,effect,FINAL CONFIDENCE GRADING,identifier
2198,atpE,atpE_p.Ala63Pro,missense_variant,2) Assoc w R - Interim,Rv1305
2201,atpE,atpE_p.Asp28Ala,missense_variant,2) Assoc w R - Interim,Rv1305
2202,atpE,atpE_p.Asp28Gly,missense_variant,2) Assoc w R - Interim,Rv1305
2203,atpE,atpE_p.Asp28Val,missense_variant,2) Assoc w R - Interim,Rv1305
2204,atpE,atpE_p.Glu61Asp,missense_variant,2) Assoc w R - Interim,Rv1305

In [29]:
print(f"Dataset shape: {data_df.shape}")  # Print the shape of the filtered dataset
print(f"Rows: {data_df.shape[0]}")  # Print the number of rows in the filtered dataset
print(f"Columns: {data_df.shape[1]}")  # Print the number of columns in the filtered dataset

Dataset shape: (411, 5)
Rows: 411
Columns: 5

In [30]:
data_df.describe()  # Display summary statistics of the filtered dataset

,gene,variant,effect,FINAL CONFIDENCE GRADING,identifier
count,411,411,411,411,411
unique,15,384,1,2,15
top,pncA,gyrB_p.Asp461Asn,missense_variant,2) Assoc w R - Interim,Rv2043c
freq,204,2,411,225,204

In [31]:
duplicated_variant = data_df[data_df.duplicated(subset=['variant'], keep=False)]  # Identify duplicated variants
duplicated_variant  # Display duplicated variants

,gene,variant,effect,FINAL CONFIDENCE GRADING,identifier
3168,Rv0678,Rv0678_p.Ala36Val,missense_variant,2) Assoc w R - Interim,Rv0678
3215,Rv0678,Rv0678_p.Asn70Asp,missense_variant,2) Assoc w R - Interim,Rv0678
3234,Rv0678,Rv0678_p.Cys46Arg,missense_variant,2) Assoc w R - Interim,Rv0678
3268,Rv0678,Rv0678_p.Gly121Arg,missense_variant,1) Assoc w R,Rv0678
3289,Rv0678,Rv0678_p.Ile67Ser,missense_variant,2) Assoc w R - Interim,Rv0678
3293,Rv0678,Rv0678_p.Leu117Arg,missense_variant,1) Assoc w R,Rv0678
3304,Rv0678,Rv0678_p.Leu32Ser,missense_variant,2) Assoc w R - Interim,Rv0678
3328,Rv0678,Rv0678_p.Met146Thr,missense_variant,2) Assoc w R - Interim,Rv0678
7656,Rv0678,Rv0678_p.Ala36Val,missense_variant,2) Assoc w R - Interim,Rv0678
7692,Rv0678,Rv0678_p.Asn70Asp,missense_variant,2) Assoc w R - Interim,Rv0678
7708,Rv0678,Rv0678_p.Cys46Arg,missense_variant,2) Assoc w R - Interim,Rv0678
7735,Rv0678,Rv0678_p.Gly121Arg,missense_variant,2) Assoc w R - Interim,Rv0678
7749,Rv0678,Rv0678_p.Ile67Ser,missense_variant,2) Assoc w R - Interim,Rv0678
7754,Rv0678,Rv0678_p.Leu117Arg,missense_variant,2) Assoc w R - Interim,Rv0678
7760,Rv0678,Rv0678_p.Leu32Ser,missense_variant,2) Assoc w R - Interim,Rv0678
7781,Rv0678,Rv0678_p.Met146Thr,missense_variant,2) Assoc w R - Interim,Rv0678
17582,inhA,inhA_p.Ser94Ala,missense_variant,2) Assoc w R - Interim,Rv1484
21180,inhA,inhA_p.Ser94Ala,missense_variant,2) Assoc w R - Interim,Rv1484
29330,gyrA,gyrA_p.Ala90Val,missense_variant,1) Assoc w R,Rv0006
29434,gyrA,gyrA_p.Asp89Asn,missense_variant,1) Assoc w R,Rv0006
29436,gyrA,gyrA_p.Asp94Ala,missense_variant,1) Assoc w R,Rv0006
29437,gyrA,gyrA_p.Asp94Asn,missense_variant,1) Assoc w R,Rv0006
29438,gyrA,gyrA_p.Asp94Gly,missense_variant,1) Assoc w R,Rv0006
29439,gyrA,gyrA_p.Asp94His,missense_variant,1) Assoc w R,Rv0006
29441,gyrA,gyrA_p.Asp94Tyr,missense_variant,1) Assoc w R,Rv0006
29525,gyrA,gyrA_p.Gly88Ala,missense_variant,2) Assoc w R - Interim,Rv0006
29528,gyrA,gyrA_p.Gly88Cys,missense_variant,1) Assoc w R,Rv0006
29655,gyrA,gyrA_p.Ser91Pro,missense_variant,1) Assoc w R,Rv0006
30014,gyrB,gyrB_p.Ala504Val,missense_variant,2) Assoc w R - Interim,Rv0005
30052,gyrB,gyrB_p.Asn499Asp,missense_variant,1) Assoc w R,Rv0005
30056,gyrB,gyrB_p.Asn499Thr,missense_variant,1) Assoc w R,Rv0005
30078,gyrB,gyrB_p.Asp461Asn,missense_variant,1) Assoc w R,Rv0005
30079,gyrB,gyrB_p.Asp461His,missense_variant,2) Assoc w R - Interim,Rv0005
30113,gyrB,gyrB_p.Glu501Asp,missense_variant,2) Assoc w R - Interim,Rv0005
30115,gyrB,gyrB_p.Glu501Val,missense_variant,2) Assoc w R - Interim,Rv0005
30237,gyrB,gyrB_p.Ser447Phe,missense_variant,2) Assoc w R - Interim,Rv0005
33236,gyrA,gyrA_p.Ala90Val,missense_variant,1) Assoc w R,Rv0006
33329,gyrA,gyrA_p.Asp89Asn,missense_variant,1) Assoc w R,Rv0006
33331,gyrA,gyrA_p.Asp94Ala,missense_variant,1) Assoc w R,Rv0006
33332,gyrA,gyrA_p.Asp94Asn,missense_variant,1) Assoc w R,Rv0006
33333,gyrA,gyrA_p.Asp94Gly,missense_variant,1) Assoc w R,Rv0006
33334,gyrA,gyrA_p.Asp94His,missense_variant,1) Assoc w R,Rv0006
33336,gyrA,gyrA_p.Asp94Tyr,missense_variant,1) Assoc w R,Rv0006
33407,gyrA,gyrA_p.Gly88Ala,missense_variant,2) Assoc w R - Interim,Rv0006
33409,gyrA,gyrA_p.Gly88Cys,missense_variant,1) Assoc w R,Rv0006
33517,gyrA,gyrA_p.Ser91Pro,missense_variant,1) Assoc w R,Rv0006
33838,gyrB,gyrB_p.Ala504Val,missense_variant,2) Assoc w R - Interim,Rv0005
33871,gyrB,gyrB_p.Asn499Asp,missense_variant,2) Assoc w R - Interim,Rv0005
33875,gyrB,gyrB_p.Asn499Thr,missense_variant,2) Assoc w R - Interim,Rv0005
33896,gyrB,gyrB_p.Asp461Asn,missense_variant,2) Assoc w R - Interim,Rv0005
33897,gyrB,gyrB_p.Asp461His,missense_variant,2) Assoc w R - Interim,Rv0005
33930,gyrB,gyrB_p.Glu501Asp,missense_variant,1) Assoc w R,Rv0005
33932,gyrB,gyrB_p.Glu501Val,missense_variant,2) Assoc w R - Interim,Rv0005
34046,gyrB,gyrB_p.Ser447Phe,missense_variant,2) Assoc w R - Interim,Rv0005

Removing duplicated variant:

In [32]:
data_df = data_df.drop_duplicates(subset=['variant'])  # Remove duplicated variants

Analyse new dataset after removing duplicates

In [33]:
data_df.head()  # Display the first few rows of the dataset after removing duplicates

,gene,variant,effect,FINAL CONFIDENCE GRADING,identifier
2198,atpE,atpE_p.Ala63Pro,missense_variant,2) Assoc w R - Interim,Rv1305
2201,atpE,atpE_p.Asp28Ala,missense_variant,2) Assoc w R - Interim,Rv1305
2202,atpE,atpE_p.Asp28Gly,missense_variant,2) Assoc w R - Interim,Rv1305
2203,atpE,atpE_p.Asp28Val,missense_variant,2) Assoc w R - Interim,Rv1305
2204,atpE,atpE_p.Glu61Asp,missense_variant,2) Assoc w R - Interim,Rv1305

In [36]:
data_filtered_df = data_df[['variant', 'gene', 'identifier']].copy()  # Keep only the 'variant', 'gene', and 'identifier' columns
data_filtered_df.head()  # Display the first few rows of the filtered dataset

              variant  gene identifier
2198  atpE_p.Ala63Pro  atpE     Rv1305
2201  atpE_p.Asp28Ala  atpE     Rv1305
2202  atpE_p.Asp28Gly  atpE     Rv1305
2203  atpE_p.Asp28Val  atpE     Rv1305
2204  atpE_p.Glu61Asp  atpE     Rv1305

In [34]:
print(f"Dataset shape: {data_df.shape}")  # Print the shape of the dataset after removing duplicates
print(f"Rows: {data_df.shape[0]}")  # Print the number of rows in the dataset after removing duplicates
print(f"Columns: {data_df.shape[1]}")  # Print the number of columns in the dataset after removing duplicates

Dataset shape: (384, 5)
Rows: 384
Columns: 5

In [37]:
data_df.describe()  # Display summary statistics of the dataset after removing duplicates

,gene,variant,effect,FINAL CONFIDENCE GRADING,identifier
count,384,384,384,384,384
unique,15,384,1,2,15
top,pncA,atpE_p.Ala63Pro,missense_variant,2) Assoc w R - Interim,Rv2043c
freq,204,1,384,208,204

In [38]:
print(f"Unique genes: {data_df['gene'].unique()}")  # Print unique genes in the dataset after removing duplicates

Unique genes: ['atpE' 'Rv0678' 'tlyA' 'ddn' 'embB' 'ethA' 'inhA' 'katG' 'gyrA' 'gyrB'
 'rplC' 'pncA' 'rpoB' 'gid' 'rpsL']

Create dataset for filtered wild type

In [39]:
wild_df = data_df[['gene', 'identifier']].copy()  # Create a copy of the 'gene' and 'identifier' columns
wild_df = wild_df.drop_duplicates(subset='gene')  # Drop duplicate rows based on the 'gene' column
wild_df['mycobrowser_url'] = 'https://mycobrowser.epfl.ch/genes/' + wild_df['identifier']  # Add a new column with URLs
wild_df.head()  # Display the first few rows of the filtered wild dataset

         gene identifier                           mycobrowser_url
2198     atpE     Rv1305  https://mycobrowser.epfl.ch/genes/Rv1305
3168   Rv0678     Rv0678  https://mycobrowser.epfl.ch/genes/Rv0678
5797     tlyA     Rv1694  https://mycobrowser.epfl.ch/genes/Rv1694
8263      ddn     Rv3547  https://mycobrowser.epfl.ch/genes/Rv3547
11524    embB     Rv3795  https://mycobrowser.epfl.ch/genes/Rv3795

In [40]:
wild_df.head()

         gene identifier                           mycobrowser_url
2198     atpE     Rv1305  https://mycobrowser.epfl.ch/genes/Rv1305
3168   Rv0678     Rv0678  https://mycobrowser.epfl.ch/genes/Rv0678
5797     tlyA     Rv1694  https://mycobrowser.epfl.ch/genes/Rv1694
8263      ddn     Rv3547  https://mycobrowser.epfl.ch/genes/Rv3547
11524    embB     Rv3795  https://mycobrowser.epfl.ch/genes/Rv3795

In [41]:
print(f"Dataset shape: {wild_df.shape}")  # Print the shape of the filtered wild dataset
print(f"Rows: {wild_df.shape[0]}")  # Print the number of rows in the filtered wild dataset
print(f"Columns: {wild_df.shape[1]}")  # Print the number of columns in the filtered wild dataset

Dataset shape: (15, 3)
Rows: 15
Columns: 3

In [42]:
wild_df.describe()  # Display summary statistics of the filtered wild dataset

        gene identifier                           mycobrowser_url
count     15         15                                        15
unique    15         15                                        15
top     atpE     Rv1305  https://mycobrowser.epfl.ch/genes/Rv1305
freq       1          1                                         1

Creating dataset for variant type:

In [43]:
variant_df = data_df[['gene', 'identifier', 'variant']].copy()  # Create a copy of the relevant columns

### Save datasets

In [45]:
wild_df.to_csv('../wild.csv', sep=';', index=False)  # Save the filtered wild dataset to a CSV file
variant_df.to_csv('../variant.csv', sep=';', index=False)  # Save the variant dataset to a CSV file