# FASTA Sequences

### Import libraries and load dependencies:

In [1]:
import requests  # Library for sending HTTP requests to fetch data from URLs.
import pandas as pd  # Library for data manipulation and analysis.
from bs4 import BeautifulSoup  # Library for parsing HTML and XML documents.

### Define global variables

In [2]:
AMINO_ACIDS = {  # Dictionary mapping single-letter amino acid codes to their full names.
    'A': 'Ala',
    'C': 'Cys',
    'D': 'Asp',
    'E': 'Glu',
    'F': 'Phe',
    'G': 'Gly',
    'H': 'His',
    'I': 'Ile',
    'K': 'Lys',
    'L': 'Leu',
    'M': 'Met',
    'N': 'Asn',
    'P': 'Pro',
    'Q': 'Gln',
    'R': 'Arg',
    'S': 'Ser',
    'T': 'Thr',
    'V': 'Val',
    'W': 'Trp',
    'Y': 'Tyr',
}
AMINO_ACIDS_REVERSE = {value: key for key, value in AMINO_ACIDS.items()}  # Reverse dictionary for mapping full names to single-letter codes.

### Load datasets:

In [3]:
wild_df = pd.read_csv('../wild.csv', sep=';')  # Load wild-type dataset from CSV file.
variant_df = pd.read_csv('../variant.csv', sep=';')  # Load variant dataset from CSV file.

### Function to fetch wild FASTA sequence from MycoBrowser and save into a file

In [11]:
def get_fasta_sequence_wild(df):
    # Iterate through each row in the DataFrame.
    for index, row in df.iterrows():
        print(f"Saving FASTA sequence... ({index+1} from {df.shape[0]})")  # Log progress.
        gene = row["gene"]  # Extract gene name from the current row.
        url = row["mycobrowser_url"]  # Extract Mycobrowser URL.
        response = requests.get(url)  # Send GET request to fetch HTML content.
        if response.status_code == 200:  # Check if the request was successful.
            soup = BeautifulSoup(response.text, 'html.parser')  # Parse HTML content.
            fasta_section = soup.find_all('pre')  # Find all <pre> tags, which may contain FASTA sequences.
            if fasta_section:  # Check if any <pre> tags were found.
                for section in fasta_section:
                    if "Mycobacterium tuberculosis H37Rv|" in section.text:  # Ensure the section contains the correct FASTA sequence.
                        fasta_sequence = section.text.strip()  # Get the FASTA sequence and remove extra spaces.
                        fasta_sequence = fasta_sequence.split("\n")[1]  # Extract only the sequence part (ignoring the header).
                        df.loc[index, "fasta"] = fasta_sequence  # Add the sequence to the DataFrame.
            else:
                print(f"FASTA sequence not available")  # Log if no FASTA section was found.
        else:
            print(f"Gene information not found")  # Log if the request failed.
    return df  # Return the updated DataFrame with FASTA sequences added.

### Getting FASTA sequence from Mycobrowser url for all wild type

In [12]:
wild_df = get_fasta_sequence_wild(wild_df)  # Fetch and save FASTA sequences for complete wild types.

Saving FASTA sequence... (1 from 15)
Saving FASTA sequence... (2 from 15)
Saving FASTA sequence... (3 from 15)
Saving FASTA sequence... (4 from 15)
Saving FASTA sequence... (5 from 15)
Saving FASTA sequence... (6 from 15)
Saving FASTA sequence... (7 from 15)
Saving FASTA sequence... (8 from 15)
Saving FASTA sequence... (9 from 15)
Saving FASTA sequence... (10 from 15)
Saving FASTA sequence... (11 from 15)
Saving FASTA sequence... (12 from 15)
Saving FASTA sequence... (13 from 15)
Saving FASTA sequence... (14 from 15)
Saving FASTA sequence... (15 from 15)

In [15]:
# remove identifier column
wild_df = wild_df.drop(columns=['identifier'])  # Drop the 'identifier' column from the DataFrame.

In [16]:
wild_df.head()  # Display the first few rows of the updated DataFrame.

,gene,mycobrowser_url,fasta
0,atpE,https://mycobrowser.epfl.ch/genes/Rv1305,MDPTIAAGALIGGGLIMAGGAIGAGIGDGVAGNALISGVARQPEAQ...
1,Rv0678,https://mycobrowser.epfl.ch/genes/Rv0678,VSVNDGVDQMGAEPDIMEFVEQMGGYFESRSLTRLAGRLLGWLLVC...
2,tlyA,https://mycobrowser.epfl.ch/genes/Rv1694,VARRARVDAELVRRGLARSRQQAAELIGAGKVRIDGLPAVKPATAV...
3,ddn,https://mycobrowser.epfl.ch/genes/Rv3547,MPKSPPRFLNSPLSDFFIKWMSRINTWMYRRNDGEGLGGTFQKIPV...
4,embB,https://mycobrowser.epfl.ch/genes/Rv3795,MTQCASRRKSTPNRAILGAFASARGTRWVATIAGLIGFVLSVATPL...

In [18]:
print(wild_df[wild_df["fasta"].isnull()]) # Log genes without FASTA sequences due to their rRNA type.

Empty DataFrame
Columns: [gene, mycobrowser_url, fasta]
Index: []

In [20]:
print(f"Dataset shape: {wild_df.shape}")  # Print the dataset's shape.
print(f"Rows: {wild_df.shape[0]}")  # Print the number of rows.
print(f"Columns: {wild_df.shape[1]}")  # Print the number of columns.

Dataset shape: (15, 3)
Rows: 15
Columns: 3

In [ ]:
wild_df.describe()  # Display summary statistics.

In [ ]:
wild_df.to_csv('../wild.csv', sep=';', index=False)  # Save the updated DataFrame to a new CSV file.

### Getting FASTA sequence for mutations

In [21]:
variant_df.head()  # Display the first few rows of the DataFrame.

   gene identifier          variant
0  atpE     Rv1305  atpE_p.Ala63Pro
1  atpE     Rv1305  atpE_p.Asp28Ala
2  atpE     Rv1305  atpE_p.Asp28Gly
3  atpE     Rv1305  atpE_p.Asp28Val
4  atpE     Rv1305  atpE_p.Glu61Asp

In [22]:
print(f"Dataset shape: {variant_df.shape}")  # Print the dataset's shape.
print(f"Rows: {variant_df.shape[0]}")  # Print the number of rows.
print(f"Columns: {variant_df.shape[1]}")  # Print the number of columns.

Dataset shape: (384, 3)
Rows: 384
Columns: 3

In [23]:
variant_df.describe()  # Display summary statistics.

        gene identifier          variant
count    384        384              384
unique    15         15              384
top     pncA    Rv2043c  atpE_p.Ala63Pro
freq     204        204                1

In [24]:
# Function to mutate a FASTA sequence based on a given mutation.
def get_fasta_mutation(fasta_selvagem, mutation):
    position = int(mutation[3:-3])  # Extract the position of the mutation.
    amino_acid = fasta_selvagem[position-1]  # Get the original amino acid at the position.
    if mutation[:3] != AMINO_ACIDS[amino_acid]:  # Check if the amino acid matches the expected value.
        print(f"Error converting fasta sequence")  # Log an error if the amino acid does not match.
        return "ERROR: amino-acid is not the same as expected"  # Return an error message.
    fasta_mutated = list(fasta_selvagem)  # Convert the FASTA sequence to a list for mutation.
    fasta_mutated[position-1] = AMINO_ACIDS_REVERSE[mutation[-3:]]  # Replace the amino acid at the position.
    fasta_mutated = ''.join(fasta_mutated)  # Convert the mutated list back to a string.
    return fasta_mutated  # Return the mutated FASTA sequence.

In [27]:
# Function to fetch and save FASTA sequences for variants.
def get_fasta_sequence_variant(df):
    for index, row in df.iterrows():
        print(f"Saving FASTA sequence... ({index+1} from {df.shape[0]})")  # Log progress.
        wild_row = wild_df[wild_df['gene'] == row['gene']]  # Find the corresponding wild type row.
        if wild_row.empty:  # Check if the wild type gene is not found.
            print(f"Gene {row['gene']} not found in wild_df")  # Log a warning.
            continue  # Skip to the next row.
        wild_fasta = wild_row['fasta'].values[0]  # Get the FASTA sequence for the wild type.
        variant = row['variant'].split('.')[1]  # Extract the mutation from the variant column.
        mutated_fasta = get_fasta_mutation(wild_fasta, variant)  # Generate the mutated FASTA sequence.
        df.at[index, 'fasta'] = mutated_fasta  # Add the mutated sequence to the DataFrame.
    return df  # Return the updated DataFrame with FASTA sequences added.

In [31]:
variant_df = get_fasta_sequence_variant(variant_df)# Fetch and save FASTA sequences for variants.
variant_df = variant_df.drop(columns=['identifier'])  # Drop the 'identifier' column from the DataFrame.

Saving FASTA sequence... (1 from 384)
Saving FASTA sequence... (2 from 384)
Saving FASTA sequence... (3 from 384)
Saving FASTA sequence... (4 from 384)
Saving FASTA sequence... (5 from 384)
Saving FASTA sequence... (6 from 384)
Saving FASTA sequence... (7 from 384)
Saving FASTA sequence... (8 from 384)
Saving FASTA sequence... (9 from 384)
Saving FASTA sequence... (10 from 384)
Saving FASTA sequence... (11 from 384)
Saving FASTA sequence... (12 from 384)
Saving FASTA sequence... (13 from 384)
Saving FASTA sequence... (14 from 384)
Saving FASTA sequence... (15 from 384)
Saving FASTA sequence... (16 from 384)
Saving FASTA sequence... (17 from 384)
Saving FASTA sequence... (18 from 384)
Saving FASTA sequence... (19 from 384)
Saving FASTA sequence... (20 from 384)
Saving FASTA sequence... (21 from 384)
Saving FASTA sequence... (22 from 384)
Saving FASTA sequence... (23 from 384)
Saving FASTA sequence... (24 from 384)
Saving FASTA sequence... (25 from 384)
Saving FASTA sequence... (26 from 384)
Saving FASTA sequence... (27 from 384)
Saving FASTA sequence... (28 from 384)
Saving FASTA sequence... (29 from 384)
Saving FASTA sequence... (30 from 384)
Saving FASTA sequence... (31 from 384)
Saving FASTA sequence... (32 from 384)
Saving FASTA sequence... (33 from 384)
Saving FASTA sequence... (34 from 384)
Saving FASTA sequence... (35 from 384)
Saving FASTA sequence... (36 from 384)
Saving FASTA sequence... (37 from 384)
Saving FASTA sequence... (38 from 384)
Saving FASTA sequence... (39 from 384)
Saving FASTA sequence... (40 from 384)
Saving FASTA sequence... (41 from 384)
Saving FASTA sequence... (42 from 384)
Saving FASTA sequence... (43 from 384)
Saving FASTA sequence... (44 from 384)
Saving FASTA sequence... (45 from 384)
Saving FASTA sequence... (46 from 384)
Saving FASTA sequence... (47 from 384)
Saving FASTA sequence... (48 from 384)
Saving FASTA sequence... (49 from 384)
Saving FASTA sequence... (50 from 384)
Saving FASTA sequence... (51 from 384)
Saving FASTA sequence... (52 from 384)
Saving FASTA sequence... (53 from 384)
Saving FASTA sequence... (54 from 384)
Saving FASTA sequence... (55 from 384)
Saving FASTA sequence... (56 from 384)
Saving FASTA sequence... (57 from 384)
Saving FASTA sequence... (58 from 384)
Saving FASTA sequence... (59 from 384)
Saving FASTA sequence... (60 from 384)
Saving FASTA sequence... (61 from 384)
Saving FASTA sequence... (62 from 384)
Saving FASTA sequence... (63 from 384)
Saving FASTA sequence... (64 from 384)
Saving FASTA sequence... (65 from 384)
Saving FASTA sequence... (66 from 384)
Saving FASTA sequence... (67 from 384)
Saving FASTA sequence... (68 from 384)
Saving FASTA sequence... (69 from 384)
Saving FASTA sequence... (70 from 384)
Saving FASTA sequence... (71 from 384)
Saving FASTA sequence... (72 from 384)
Saving FASTA sequence... (73 from 384)
Saving FASTA sequence... (74 from 384)
Saving FASTA sequence... (75 from 384)
Saving FASTA sequence... (76 from 384)
Saving FASTA sequence... (77 from 384)
Saving FASTA sequence... (78 from 384)
Saving FASTA sequence... (79 from 384)
Saving FASTA sequence... (80 from 384)
Saving FASTA sequence... (81 from 384)
Saving FASTA sequence... (82 from 384)
Saving FASTA sequence... (83 from 384)
Saving FASTA sequence... (84 from 384)
Saving FASTA sequence... (85 from 384)
Saving FASTA sequence... (86 from 384)
Saving FASTA sequence... (87 from 384)
Saving FASTA sequence... (88 from 384)
Saving FASTA sequence... (89 from 384)
Saving FASTA sequence... (90 from 384)
Saving FASTA sequence... (91 from 384)
Saving FASTA sequence... (92 from 384)
Saving FASTA sequence... (93 from 384)
Saving FASTA sequence... (94 from 384)
Saving FASTA sequence... (95 from 384)
Saving FASTA sequence... (96 from 384)
Saving FASTA sequence... (97 from 384)
Saving FASTA sequence... (98 from 384)
Saving FASTA sequence... (99 from 384)
Saving FASTA sequence... (100 from 384)
Saving FASTA sequence... (101 from 384)
Saving FASTA sequence... (102 from 384)
Saving FASTA sequence... (103 from 384)
Saving FASTA sequence... (104 from 384)
Saving FASTA sequence... (105 from 384)
Saving FASTA sequence... (106 from 384)
Saving FASTA sequence... (107 from 384)
Saving FASTA sequence... (108 from 384)
Saving FASTA sequence... (109 from 384)
Saving FASTA sequence... (110 from 384)
Saving FASTA sequence... (111 from 384)
Saving FASTA sequence... (112 from 384)
Saving FASTA sequence... (113 from 384)
Saving FASTA sequence... (114 from 384)
Saving FASTA sequence... (115 from 384)
Saving FASTA sequence... (116 from 384)
Saving FASTA sequence... (117 from 384)
Saving FASTA sequence... (118 from 384)
Saving FASTA sequence... (119 from 384)
Saving FASTA sequence... (120 from 384)
Saving FASTA sequence... (121 from 384)
Saving FASTA sequence... (122 from 384)
Saving FASTA sequence... (123 from 384)
Saving FASTA sequence... (124 from 384)
Saving FASTA sequence... (125 from 384)
Saving FASTA sequence... (126 from 384)
Saving FASTA sequence... (127 from 384)
Saving FASTA sequence... (128 from 384)
Saving FASTA sequence... (129 from 384)
Saving FASTA sequence... (130 from 384)
Saving FASTA sequence... (131 from 384)
Saving FASTA sequence... (132 from 384)
Saving FASTA sequence... (133 from 384)
Saving FASTA sequence... (134 from 384)
Saving FASTA sequence... (135 from 384)
Saving FASTA sequence... (136 from 384)
Saving FASTA sequence... (137 from 384)
Saving FASTA sequence... (138 from 384)
Saving FASTA sequence... (139 from 384)
Saving FASTA sequence... (140 from 384)
Saving FASTA sequence... (141 from 384)
Saving FASTA sequence... (142 from 384)
Saving FASTA sequence... (143 from 384)
Saving FASTA sequence... (144 from 384)
Saving FASTA sequence... (145 from 384)
Saving FASTA sequence... (146 from 384)
Saving FASTA sequence... (147 from 384)
Saving FASTA sequence... (148 from 384)
Saving FASTA sequence... (149 from 384)
Saving FASTA sequence... (150 from 384)
Saving FASTA sequence... (151 from 384)
Saving FASTA sequence... (152 from 384)
Saving FASTA sequence... (153 from 384)
Saving FASTA sequence... (154 from 384)
Saving FASTA sequence... (155 from 384)
Saving FASTA sequence... (156 from 384)
Saving FASTA sequence... (157 from 384)
Saving FASTA sequence... (158 from 384)
Saving FASTA sequence... (159 from 384)
Saving FASTA sequence... (160 from 384)
Saving FASTA sequence... (161 from 384)
Saving FASTA sequence... (162 from 384)
Saving FASTA sequence... (163 from 384)
Saving FASTA sequence... (164 from 384)
Saving FASTA sequence... (165 from 384)
Saving FASTA sequence... (166 from 384)
Saving FASTA sequence... (167 from 384)
Saving FASTA sequence... (168 from 384)
Saving FASTA sequence... (169 from 384)
Saving FASTA sequence... (170 from 384)
Saving FASTA sequence... (171 from 384)
Saving FASTA sequence... (172 from 384)
Saving FASTA sequence... (173 from 384)
Saving FASTA sequence... (174 from 384)
Saving FASTA sequence... (175 from 384)
Saving FASTA sequence... (176 from 384)
Saving FASTA sequence... (177 from 384)
Saving FASTA sequence... (178 from 384)
Saving FASTA sequence... (179 from 384)
Saving FASTA sequence... (180 from 384)
Saving FASTA sequence... (181 from 384)
Saving FASTA sequence... (182 from 384)
Saving FASTA sequence... (183 from 384)
Saving FASTA sequence... (184 from 384)
Saving FASTA sequence... (185 from 384)
Saving FASTA sequence... (186 from 384)
Saving FASTA sequence... (187 from 384)
Saving FASTA sequence... (188 from 384)
Saving FASTA sequence... (189 from 384)
Saving FASTA sequence... (190 from 384)
Saving FASTA sequence... (191 from 384)
Saving FASTA sequence... (192 from 384)
Saving FASTA sequence... (193 from 384)
Saving FASTA sequence... (194 from 384)
Saving FASTA sequence... (195 from 384)
Saving FASTA sequence... (196 from 384)
Saving FASTA sequence... (197 from 384)
Saving FASTA sequence... (198 from 384)
Saving FASTA sequence... (199 from 384)
Saving FASTA sequence... (200 from 384)
Saving FASTA sequence... (201 from 384)
Saving FASTA sequence... (202 from 384)
Saving FASTA sequence... (203 from 384)
Saving FASTA sequence... (204 from 384)
Saving FASTA sequence... (205 from 384)
Saving FASTA sequence... (206 from 384)
Saving FASTA sequence... (207 from 384)
Saving FASTA sequence... (208 from 384)
Saving FASTA sequence... (209 from 384)
Saving FASTA sequence... (210 from 384)
Saving FASTA sequence... (211 from 384)
Saving FASTA sequence... (212 from 384)
Saving FASTA sequence... (213 from 384)
Saving FASTA sequence... (214 from 384)
Saving FASTA sequence... (215 from 384)
Saving FASTA sequence... (216 from 384)
Saving FASTA sequence... (217 from 384)
Saving FASTA sequence... (218 from 384)
Saving FASTA sequence... (219 from 384)
Saving FASTA sequence... (220 from 384)
Saving FASTA sequence... (221 from 384)
Saving FASTA sequence... (222 from 384)
Saving FASTA sequence... (223 from 384)
Saving FASTA sequence... (224 from 384)
Saving FASTA sequence... (225 from 384)
Saving FASTA sequence... (226 from 384)
Saving FASTA sequence... (227 from 384)
Saving FASTA sequence... (228 from 384)
Saving FASTA sequence... (229 from 384)
Saving FASTA sequence... (230 from 384)
Saving FASTA sequence... (231 from 384)
Saving FASTA sequence... (232 from 384)
Saving FASTA sequence... (233 from 384)
Saving FASTA sequence... (234 from 384)
Saving FASTA sequence... (235 from 384)
Saving FASTA sequence... (236 from 384)
Saving FASTA sequence... (237 from 384)
Saving FASTA sequence... (238 from 384)
Saving FASTA sequence... (239 from 384)
Saving FASTA sequence... (240 from 384)
Saving FASTA sequence... (241 from 384)
Saving FASTA sequence... (242 from 384)
Saving FASTA sequence... (243 from 384)
Saving FASTA sequence... (244 from 384)
Saving FASTA sequence... (245 from 384)
Saving FASTA sequence... (246 from 384)
Saving FASTA sequence... (247 from 384)
Saving FASTA sequence... (248 from 384)
Saving FASTA sequence... (249 from 384)
Saving FASTA sequence... (250 from 384)
Saving FASTA sequence... (251 from 384)
Saving FASTA sequence... (252 from 384)
Saving FASTA sequence... (253 from 384)
Saving FASTA sequence... (254 from 384)
Saving FASTA sequence... (255 from 384)
Saving FASTA sequence... (256 from 384)
Saving FASTA sequence... (257 from 384)
Saving FASTA sequence... (258 from 384)
Saving FASTA sequence... (259 from 384)
Saving FASTA sequence... (260 from 384)
Saving FASTA sequence... (261 from 384)
Saving FASTA sequence... (262 from 384)
Saving FASTA sequence... (263 from 384)
Saving FASTA sequence... (264 from 384)
Saving FASTA sequence... (265 from 384)
Saving FASTA sequence... (266 from 384)
Saving FASTA sequence... (267 from 384)
Saving FASTA sequence... (268 from 384)
Saving FASTA sequence... (269 from 384)
Saving FASTA sequence... (270 from 384)
Saving FASTA sequence... (271 from 384)
Saving FASTA sequence... (272 from 384)
Saving FASTA sequence... (273 from 384)
Saving FASTA sequence... (274 from 384)
Saving FASTA sequence... (275 from 384)
Saving FASTA sequence... (276 from 384)
Saving FASTA sequence... (277 from 384)
Saving FASTA sequence... (278 from 384)
Saving FASTA sequence... (279 from 384)
Saving FASTA sequence... (280 from 384)
Saving FASTA sequence... (281 from 384)
Saving FASTA sequence... (282 from 384)
Saving FASTA sequence... (283 from 384)
Saving FASTA sequence... (284 from 384)
Saving FASTA sequence... (285 from 384)
Saving FASTA sequence... (286 from 384)
Saving FASTA sequence... (287 from 384)
Saving FASTA sequence... (288 from 384)
Saving FASTA sequence... (289 from 384)
Saving FASTA sequence... (290 from 384)
Saving FASTA sequence... (291 from 384)
Saving FASTA sequence... (292 from 384)
Saving FASTA sequence... (293 from 384)
Saving FASTA sequence... (294 from 384)
Saving FASTA sequence... (295 from 384)
Saving FASTA sequence... (296 from 384)
Saving FASTA sequence... (297 from 384)
Saving FASTA sequence... (298 from 384)
Saving FASTA sequence... (299 from 384)
Saving FASTA sequence... (300 from 384)
Saving FASTA sequence... (301 from 384)
Saving FASTA sequence... (302 from 384)
Saving FASTA sequence... (303 from 384)
Saving FASTA sequence... (304 from 384)
Saving FASTA sequence... (305 from 384)
Saving FASTA sequence... (306 from 384)
Saving FASTA sequence... (307 from 384)
Saving FASTA sequence... (308 from 384)
Saving FASTA sequence... (309 from 384)
Saving FASTA sequence... (310 from 384)
Saving FASTA sequence... (311 from 384)
Saving FASTA sequence... (312 from 384)
Saving FASTA sequence... (313 from 384)
Saving FASTA sequence... (314 from 384)
Saving FASTA sequence... (315 from 384)
Saving FASTA sequence... (316 from 384)
Saving FASTA sequence... (317 from 384)
Saving FASTA sequence... (318 from 384)
Saving FASTA sequence... (319 from 384)
Saving FASTA sequence... (320 from 384)
Saving FASTA sequence... (321 from 384)
Saving FASTA sequence... (322 from 384)
Saving FASTA sequence... (323 from 384)
Saving FASTA sequence... (324 from 384)
Saving FASTA sequence... (325 from 384)
Saving FASTA sequence... (326 from 384)
Saving FASTA sequence... (327 from 384)
Saving FASTA sequence... (328 from 384)
Saving FASTA sequence... (329 from 384)
Saving FASTA sequence... (330 from 384)
Saving FASTA sequence... (331 from 384)
Saving FASTA sequence... (332 from 384)
Saving FASTA sequence... (333 from 384)
Saving FASTA sequence... (334 from 384)
Saving FASTA sequence... (335 from 384)
Saving FASTA sequence... (336 from 384)
Saving FASTA sequence... (337 from 384)
Saving FASTA sequence... (338 from 384)
Saving FASTA sequence... (339 from 384)
Saving FASTA sequence... (340 from 384)
Saving FASTA sequence... (341 from 384)
Saving FASTA sequence... (342 from 384)
Saving FASTA sequence... (343 from 384)
Saving FASTA sequence... (344 from 384)
Saving FASTA sequence... (345 from 384)
Saving FASTA sequence... (346 from 384)
Saving FASTA sequence... (347 from 384)
Saving FASTA sequence... (348 from 384)
Saving FASTA sequence... (349 from 384)
Saving FASTA sequence... (350 from 384)
Saving FASTA sequence... (351 from 384)
Saving FASTA sequence... (352 from 384)
Saving FASTA sequence... (353 from 384)
Saving FASTA sequence... (354 from 384)
Saving FASTA sequence... (355 from 384)
Saving FASTA sequence... (356 from 384)
Saving FASTA sequence... (357 from 384)
Saving FASTA sequence... (358 from 384)
Saving FASTA sequence... (359 from 384)
Saving FASTA sequence... (360 from 384)
Saving FASTA sequence... (361 from 384)
Saving FASTA sequence... (362 from 384)
Saving FASTA sequence... (363 from 384)
Saving FASTA sequence... (364 from 384)
Saving FASTA sequence... (365 from 384)
Saving FASTA sequence... (366 from 384)
Saving FASTA sequence... (367 from 384)
Saving FASTA sequence... (368 from 384)
Saving FASTA sequence... (369 from 384)
Saving FASTA sequence... (370 from 384)
Saving FASTA sequence... (371 from 384)
Saving FASTA sequence... (372 from 384)
Saving FASTA sequence... (373 from 384)
Saving FASTA sequence... (374 from 384)
Saving FASTA sequence... (375 from 384)
Saving FASTA sequence... (376 from 384)
Saving FASTA sequence... (377 from 384)
Saving FASTA sequence... (378 from 384)
Saving FASTA sequence... (379 from 384)
Saving FASTA sequence... (380 from 384)
Saving FASTA sequence... (381 from 384)
Saving FASTA sequence... (382 from 384)
Saving FASTA sequence... (383 from 384)
Saving FASTA sequence... (384 from 384)

In [32]:
variant_df.head()  # Display the first few rows of the DataFrame.

   gene          variant                                              fasta
0  atpE  atpE_p.Ala63Pro  MDPTIAAGALIGGGLIMAGGAIGAGIGDGVAGNALISGVARQPEAQ...
1  atpE  atpE_p.Asp28Ala  MDPTIAAGALIGGGLIMAGGAIGAGIGAGVAGNALISGVARQPEAQ...
2  atpE  atpE_p.Asp28Gly  MDPTIAAGALIGGGLIMAGGAIGAGIGGGVAGNALISGVARQPEAQ...
3  atpE  atpE_p.Asp28Val  MDPTIAAGALIGGGLIMAGGAIGAGIGVGVAGNALISGVARQPEAQ...
4  atpE  atpE_p.Glu61Asp  MDPTIAAGALIGGGLIMAGGAIGAGIGDGVAGNALISGVARQPEAQ...

In [30]:
print(f"Dataset shape: {variant_df.shape}")  # Print the dataset's shape.
print(f"Rows: {variant_df.shape[0]}")  # Print the number of rows.
print(f"Columns: {variant_df.shape[1]}")  # Print the number of columns.

Dataset shape: (384, 4)
Rows: 384
Columns: 4

In [ ]:
variant_df.describe() # Display summary statistics.

In [ ]:
variant_df.to_csv(f"../variant.csv", index=False, sep=';') # Save the updated DataFrame with FASTA sequences to a CSV file.